language: erlang
sudo: false
otp_release:
# Test on all the latest releases for the major versions supported as specified by the `require_otp_vsn` in rebar.config
   - 20.0
   - 19.3
   - 18.0
   - 17.4
   - R16B03-1
#  - R15B03-1 not available on travis
   - R15B03

script: 
  - "[ ! -d deps/merl ] || make -C deps/merl && make check"

notifications:
  irc: "chat.freenode.net#erlydtl"
  email: false
